int *generateArray(int n);
double *generateDoubleArray(int n);
void printArray(int A[], int size);
void printDoubleArray(double* A, int size);
int *copyIntArr(int *arr, int size);
double *copyDoubleArr(double *arr, int size);
void writeToFile();
double euclidDist(int d, double* p1, double* p2);
double colStd(double *arr, double avg, int index, int rowlen, int collen);
double avg(double*arr,int size);
